name: rx_dart
description: A new Flutter project.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  rxdart: ^0.27.3
  flutter_hooks: ^0.18.4
  firebase_core: ^1.18.0
  firebase_auth: ^3.3.20
  cloud_firestore: ^3.1.18
  uuid: ^3.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/text/cats.txt
    - assets/text/dogs.txt


